title = "Free and open source silicon (FOSSi)"

[[links]]
name = "ChipFoundry"
href = "https://chipfoundry.io/"

[[links]]
name = "Zero ASIC"
href = "https://www.zeroasic.com/"

[[links]]
name = "OpenTitan"
href = "https://opentitan.org/"

[[links]]
name = "CHIPS Alliance"
href = "https://chipsalliance.org/"
